name: memories-server-ec2-instance
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.AWS_HOSTNAME}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.AWS_USERNAME }}
          script: |
                sudo apt-get update
                cd memories-server-instance
                npm i
                sudo npm install pm2 -g
                pm2 start index.js
                sudo systemctl reload nginx
